name: flutter_localization_example
description: A Flutter localization example.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.17.1

flutter:
  uses-material-design: true
