language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - sys-img-armeabi-v7a-android-25

before_install:
  - mkdir "$ANDROID_HOME/licenses" || true
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew clean build

notifications:
  email: false
